version: '3.8'

services:
  app:
    build:
      context: .  # Specify the build context to your API folder
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/flask_app_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
